function paths = project_paths(anchor_path)
%PROJECT_PATHS Resolve repository-relative directories for the DCM pipeline.

if nargin < 1 || isempty(anchor_path)
    anchor_path = mfilename('fullpath');
end

if isfile(anchor_path)
    anchor_dir = fileparts(anchor_path);
else
    anchor_dir = anchor_path;
end

repo_root = fileparts(anchor_dir);

paths = struct( ...
    'repo_root', repo_root, ...
    'data_root', fullfile(repo_root, 'data'), ...
    'fmriprep_root', fullfile(repo_root, 'data', 'fmriprep'), ...
    'masks_root', fullfile(repo_root, 'data', 'masks'), ...
    'onsets_root', fullfile(repo_root, 'data', 'onsets', 'concatenated'), ...
    'output_root', fullfile(repo_root, 'data', 'output'), ...
    'results_root', fullfile(repo_root, 'results') ...
);
end
